on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout
    - name: Test
      run: go test -race ./...